name: crawl tv live source & release

on:
  schedule:
    - cron: '0 8 * * *'
  push:
    branches:
      - main
  pull_request:
    types:
      - opened

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup node env
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn

      - name: run cypress
        run: yarn cy:run

      - name: commit generated files
        run: |
          git config --local user.email "plmmilove@foxmail.com"
          git config --local user.name "plmmilove"
          git add dist/*.m3u
          git commit dist/*.m3u -m "Add generated file"
          git push -f

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist